name: me0segreco-py311
channels:
  - conda-forge
dependencies:
  - python=3.11.11
  - pytorch=2.6.0
  - lightning=2.5.1
  - torchmetrics=1.7.0
  - jsonargparse
  - h5py=3.13.0
  - matplotlib
  - scienceplots
  - mplhep
  - hist
  - mplhep
  - pandas
  - statsmodels
  - jupyterlab
  - typeshed-client
  - einops
  - pip
  - pip:
    - tensordict==0.7.2

